name: 01-Building-Blocks  
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:  
      - name: succeed
        run: echo "This step always succeeds"
      - name: Say Goodbye
        run: echo "Goodbye, World!"
