name: 02-workflow-events  
on: push # Trigger the workflow on push events to any branch
   
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show Trigger Event
        run: echo "I've been triggered by a(name): ${{ github.event_name }} event."
 